#Server port :
server.port= 8815

#Application name :
spring.application.name= category-service

#Client registration properties :
eureka.client.service-url.defaultZone = http://localhost:8761/eureka

#Data source :
# Hỗ trợ lưu tiếng Việt vào SQL Server
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=category_service;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Jpa/Hibernate :
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.hibernate.ddl-auto=update