#Server port :
server.port= 8810

#Application name :
spring.application.name= product-catalog-service

#Client registration properties :
eureka.client.service-url.defaultZone = http://localhost:8761/eureka

#Data source :
# Sửa lại dòng cấu hình url thành như vầy:
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=product_catalog;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Jpa/Hibernate :
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.hibernate.ddl-auto = update

#clound-image
cloudinary.cloud-name=dz2rksjoz
cloudinary.api-key=653385526886626
cloudinary.api-secret=DMFI06yoLqv4cLkxyoa38lxiLU0